# Generated by Django 2.2.4 on 2019-11-06 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 19, 32, 36, 252843, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
